<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <OutputType>Library</OutputType>
    <RootNamespace>CampusLibraryApi</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- API Versioning -->
    <!-- Versioning -->
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0"/>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0"/>
    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CampusLibraryApi_2_BuildingBlocks\CampusLibraryApi_2_BuildingBlocks.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_3_Core_Catalog\CampusLibraryApi_3_Core_Catalog.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_3_Core_Loan\CampusLibraryApi_3_Core_Loan.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_3_Core_Readers\CampusLibraryApi_3_Core_Readers.csproj" />
  </ItemGroup>
  
</Project>