<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <RootNamespace>CampusLibraryApi</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- API Versioning -->
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0"/>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0"/>
    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7"/>
    <!-- Entity Framework Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8"/>
    <!-- SQLite provider for EF Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8"/>
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="_2_BuildingBlocks\_3_Domain\Enums\" />
    <Folder Include="_2_BuildingBlocks\_3_Domain\ValueObjects\" />
    <Folder Include="_3_Core\" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
