<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <RootNamespace>CampusLibraryApi</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <!-- API Versioning -->
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0"/>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0"/>
    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7"/>
<!--    &lt;!&ndash; Entity Framework Core &ndash;&gt;-->
<!--    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">-->
<!--      <PrivateAssets>all</PrivateAssets>-->
<!--      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
<!--    </PackageReference>-->
<!--    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8"/>-->
<!--    &lt;!&ndash; SQLite provider for EF Core &ndash;&gt;-->
<!--    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8"/>-->
  </ItemGroup>
  
  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\CampusLibraryApi_1_Web\CampusLibraryApi_1_Web.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_2_BuildingBlocks\CampusLibraryApi_2_BuildingBlocks.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_3_Core_Readers\CampusLibraryApi_3_Core_Readers.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_4_Infrastructure\CampusLibraryApi_4_Infrastructure.csproj" />
  </ItemGroup>

</Project>
