@baseUrl = http://localhost:5000/library/v1

### 
# create reader 1
POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "firstname": "Erika",
  "lastname": "Mustermann",
  "email": "e.mustermann@t-online.de",
  "addressDto": {
    "street": "Hauptstr. 12",
    "postalCode": "29556",
    "city": "Suderburg",
    "country": "DE"
  },
  "subject": "reader-001",
  "id": "10000000-0000-0000-0000-000000000000"
}

###
# create reader 2
POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "firstname": "Max",
  "lastname": "Mustermann",
  "email": "m.mustermann@gmail.com",
  "addressDto": {
    "street": "Hauptstr. 12",
    "postalCode": "29556",
    "city": "Suderburg",
    "country": "DE"
  },
  "subject": "reader-002",
  "id": "20000000-0000-0000-0000-000000000000"
}

###
#
POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "firstname": "Arne",
  "lastname": "Arndt",
  "email": "a.arndt@t-online.de",
  "addressDto": {
    "street": "Neuperverstr. 29",
    "postalCode": "29410",
    "city": "Salzwedel",
    "country": "DE"
  },
  "subject": "reader-003",
  "id": null
}


### 
# Reader: Get all
GET {{baseUrl}}/readers
Accept: application/json


###
#Reader: Get by Id
GET {{baseUrl}}/readers/10000000-0000-0000-0000-000000000000
Accept: application/json

###
#Reader: Get by Id
GET {{baseUrl}}/readers/20000000-0000-0000-0000-000000000000
Accept: application/json


###
# Reader: Get reader 1 by Email
GET {{baseUrl}}/readers/email?email=e.mustermann@t-online.de
Accept: application/json

###
# Reader: Get reader 2 by Email
GET {{baseUrl}}/readers/email?email=m.mustermann@gmail.com
Accept: application/json

### ---------------------------------------------------------------------------
# Negative Test: Create duplicate subject
POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-002",
  "firstname": "Erika",
  "lastname": "Meier",
  "email": "duplicate.subject@example.com",
  "addressDto": {
    "street": "Neue Straße 1",
    "postalCode": "11111",
    "city": "Teststadt",
    "country": "Germany"
  },
  "id": null
}


###
# Negative Test: Create duplicate email

POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-003",
  "firstname": "Erika",
  "lastname": "Meier",
  "email": "{{readerEmail}}",
  "addressDto": {
    "street": "Neue Straße 1",
    "postalCode": "11111",
    "city": "Teststadt",
    "country": "Germany"
  },
  "id": null
}


### ---------------------------------------------------------------------------
### Negative Test: Get by unknown Id
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found

GET {{baseUrl}}/readers/99999999-9999-9999-9999-999999999999
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Get by unknown Email
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found

GET {{baseUrl}}/readers/email?email=unknown@example.com
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Get by invalid Email
### ---------------------------------------------------------------------------
# Erwartung:
# - 400 Bad Request
# Falls der Controller DomainError.Status korrekt auf HTTP abbildet.
# Wenn aktuell noch hart NotFound(...) verwendet wird, kommt hier vermutlich falsch 404.

GET {{baseUrl}}/readers/email?email=invalid-email
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Create invalid firstname
### ---------------------------------------------------------------------------
# Erwartung:
# - 400 Bad Request

POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-004",
  "firstname": "A",
  "lastname": "Mustermann",
  "email": "reader004@example.com",
  "addressDto": {
    "street": "Musterstraße 12",
    "postalCode": "12345",
    "city": "Musterstadt",
    "country": "Germany"
  },
  "id": null
}


### ---------------------------------------------------------------------------
### Negative Test: Create invalid Id
### ---------------------------------------------------------------------------
# Erwartung:
# - 400 Bad Request

POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-005",
  "firstname": "Max",
  "lastname": "Mustermann",
  "email": "reader005@example.com",
  "addressDto": {
    "street": "Musterstraße 12",
    "postalCode": "12345",
    "city": "Musterstadt",
    "country": "Germany"
  },
  "id": "not-a-guid"
}