@baseUrl = https://localhost:8010/camplib/v1

@reader1Id = 10000000-0000-0000-0000-000000000000
@reader2Id = 20000000-0000-0000-0000-000000000000
@unknownReaderId = 99999999-9999-9999-9999-999999999999

@reader1Email = e.mustermann@t-online.de
@reader2Email = m.mustermann@gmail.com

### ---------------------------------------------------------------------------
### Create reader 1
### ---------------------------------------------------------------------------
POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "firstname": "Erika",
  "lastname": "Mustermann",
  "email": "{{reader1Email}}",
  "addressDto": {
    "street": "Hauptstr. 12",
    "postalCode": "29556",
    "city": "Suderburg",
    "country": "DE"
  },
  "subject": "reader-001",
  "id": "{{reader1Id}}"
}


### ---------------------------------------------------------------------------
### Create reader 2
### ---------------------------------------------------------------------------
POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "firstname": "Max",
  "lastname": "Mustermann",
  "email": "{{reader2Email}}",
  "addressDto": {
    "street": "Hauptstr. 12",
    "postalCode": "29556",
    "city": "Suderburg",
    "country": "DE"
  },
  "subject": "reader-002",
  "id": "{{reader2Id}}"
}


### ---------------------------------------------------------------------------
### Create reader 3 with generated id
### ---------------------------------------------------------------------------
POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "firstname": "Arne",
  "lastname": "Arndt",
  "email": "a.arndt@t-online.de",
  "addressDto": {
    "street": "Neuperverstr. 29",
    "postalCode": "29410",
    "city": "Salzwedel",
    "country": "DE"
  },
  "subject": "reader-003",
  "id": null
}


### ---------------------------------------------------------------------------
### Reader: Get all active readers
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get all readers including inactive readers
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers/with-inactive
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get active reader 1 by id
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers/{{reader1Id}}
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get active reader 2 by id
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers/{{reader2Id}}
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get reader 1 by id including inactive readers
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers/{{reader1Id}}/with-inactive
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get reader 1 by email
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers/email?email={{reader1Email}}
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get reader 2 by email
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers/email?email={{reader2Email}}
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Update reader 1
### ---------------------------------------------------------------------------
PUT {{baseUrl}}/readers/{{reader1Id}}
Content-Type: application/json
Accept: application/json

{
  "lastname": "Meier",
  "email": "e.meier@gmx.de",
  "addressDto": {
    "street": "Neue Straße 5",
    "postalCode": "30123",
    "city": "Hannover",
    "country": "DE"
  }
}


### ---------------------------------------------------------------------------
### Reader: Get updated active reader 1 by id
### ---------------------------------------------------------------------------
GET {{baseUrl}}/readers/{{reader1Id}}
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Deactivate reader 1
### ---------------------------------------------------------------------------
# Erwartung:
# - 204 No Content
# - Reader bleibt in der Datenbank erhalten
# - Reader verschwindet aus normalen ReadModel-Abfragen
# - Reader ist über WithInactive-Endpunkte weiterhin sichtbar

DELETE {{baseUrl}}/readers/{{reader1Id}}
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get deactivated reader 1 by normal id endpoint
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found
# Der normale Details-Endpunkt liefert nur aktive Reader.

GET {{baseUrl}}/readers/{{reader1Id}}
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get deactivated reader 1 including inactive readers
### ---------------------------------------------------------------------------
# Erwartung:
# - 200 OK
# - isActive ist false

GET {{baseUrl}}/readers/{{reader1Id}}/with-inactive
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get all active readers after deactivation
### ---------------------------------------------------------------------------
# Erwartung:
# - 200 OK
# - Reader 1 ist nicht mehr enthalten

GET {{baseUrl}}/readers
Accept: application/json


### ---------------------------------------------------------------------------
### Reader: Get all readers including inactive readers after deactivation
### ---------------------------------------------------------------------------
# Erwartung:
# - 200 OK
# - Reader 1 ist weiterhin enthalten
# - isActive von Reader 1 ist false

GET {{baseUrl}}/readers/with-inactive
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Deactivate already inactive reader
### ---------------------------------------------------------------------------
# Erwartung:
# - 409 Conflict
# Falls ReaderErrors.IsAlreadyDeactivated den Status Conflict verwendet.

DELETE {{baseUrl}}/readers/{{reader1Id}}
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Deactivate unknown reader
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found

DELETE {{baseUrl}}/readers/{{unknownReaderId}}
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Deactivate invalid id
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found durch Routing,
#   weil "not-a-guid" nicht zur Route {id:guid} passt.

DELETE {{baseUrl}}/readers/not-a-guid
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Create duplicate subject
### ---------------------------------------------------------------------------
# Erwartung:
# - 409 Conflict

POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-002",
  "firstname": "Erika",
  "lastname": "Meier",
  "email": "duplicate.subject@example.com",
  "addressDto": {
    "street": "Neue Straße 1",
    "postalCode": "11111",
    "city": "Teststadt",
    "country": "DE"
  },
  "id": null
}


### ---------------------------------------------------------------------------
### Negative Test: Create duplicate email
### ---------------------------------------------------------------------------
# Erwartung:
# - 409 Conflict

POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-004",
  "firstname": "Erika",
  "lastname": "Meier",
  "email": "{{reader2Email}}",
  "addressDto": {
    "street": "Neue Straße 1",
    "postalCode": "11111",
    "city": "Teststadt",
    "country": "DE"
  },
  "id": null
}


### ---------------------------------------------------------------------------
### Negative Test: Get by unknown id
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found

GET {{baseUrl}}/readers/{{unknownReaderId}}
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Get by unknown id including inactive readers
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found

GET {{baseUrl}}/readers/{{unknownReaderId}}/with-inactive
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Get by unknown email
### ---------------------------------------------------------------------------
# Erwartung:
# - 404 Not Found

GET {{baseUrl}}/readers/email?email=unknown@example.com
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Get by invalid email
### ---------------------------------------------------------------------------
# Erwartung:
# - 400 Bad Request

GET {{baseUrl}}/readers/email?email=invalid-email
Accept: application/json


### ---------------------------------------------------------------------------
### Negative Test: Create invalid firstname
### ---------------------------------------------------------------------------
# Erwartung:
# - 400 Bad Request

POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-005",
  "firstname": "A",
  "lastname": "Mustermann",
  "email": "reader005@example.com",
  "addressDto": {
    "street": "Musterstraße 12",
    "postalCode": "12345",
    "city": "Musterstadt",
    "country": "DE"
  },
  "id": null
}


### ---------------------------------------------------------------------------
### Negative Test: Create invalid id
### ---------------------------------------------------------------------------
# Erwartung:
# - 400 Bad Request

POST {{baseUrl}}/readers
Content-Type: application/json
Accept: application/json

{
  "subject": "reader-006",
  "firstname": "Max",
  "lastname": "Mustermann",
  "email": "reader006@example.com",
  "addressDto": {
    "street": "Musterstraße 12",
    "postalCode": "12345",
    "city": "Musterstadt",
    "country": "DE"
  },
  "id": "not-a-guid"
}