<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>CampusLibraryApi</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Entity Framework Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9"/>
    <!-- SQLite provider for EF Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9"/>
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="[3.50.3]"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CampusLibraryApi_3_Core_Catalog\CampusLibraryApi_3_Core_Catalog.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_3_Core_Loan\CampusLibraryApi_3_Core_Loan.csproj" />
    <ProjectReference Include="..\CampusLibraryApi_3_Core_Readers\CampusLibraryApi_3_Core_Readers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="_4_Infrastructure\Security\" />
  </ItemGroup>

</Project>
