### @name Set Params
@subject =  00000003-0000-0001-0000-000000000000
@email = a.arndt@t-online.de
@password = Geh1m_
@mustChangePassword = false
@accountType = reader
@createdAt = 2025-01-01T00:00:00Z

@readerId = 00000003-0000-0000-0000-000000000000
@firstname = Arne
@lastname = Arndt
@street = Neuperverstr. 29
@postalCode = 29410
@city = Salzwedel
# JSON: keep quotes for text, set to null
@country = "DE"

### 
run ReaderProvisionTemplate.http